name: Release Build

### -- リリースタグがセットされたら実行
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.15.0"
      - name: Install dependencies
        run: npm install
        # npm ci は使わない。
      - name: Build
        run: npm run export
      - name: zipper
        run: |
          cd out
          zip release.zip **
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./out/release.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          draft: true
